// Public client configuration only. Never place private keys or credentials here.
// Keep disabled until the mint, rewards vault, hook program, and RPC are
// independently verified. No direct treasury transfer is supported.
window.TLAMA_PAYMENT_CONFIG = {
  dashboard_url: "",
  enabled: false,
  web3_enabled: false,
  mint_address: "",
  destination_address: "",
  destination_label: "10% Game Rewards Vault",
  reward_vault_address: "",
  hook_program_address: "",
  rpc_url: "",
  raydium_api: "",
  swap_slippage_bps: 100,
  decimals: 9,
  game_economy: {
    entry_fee_tlama: 25,
    entry_fee_required: true,
    settlement_mode: "audited-transfer-hook-required",
    reward_vault_percent: 100,
    reward_vault_label: "10% Game Rewards Vault",
    reward_vault_address: "",
    hook_program_address: "",
    catalog: [
      {
        id: "arcade-entry-fee",
        kind: "entry",
        label: "In-Game Entry Fee",
        target_usd: "0.25",
        pricing: "mock-token-price-usd",
        amount_tlama: 25,
        description: "Required once per arcade match.",
      },
      {
        id: "heart-matrix-upgrade",
        kind: "utility",
        label: "Heart Matrix Upgrade",
        target_usd: "1.50",
        pricing: "mock-token-price-usd",
        amount_tlama: 150,
        description: "Adds one life to this match, up to two upgrades.",
        unlock_level: 6,
        max_per_match: 2,
      },
      {
        id: "llama-character-skins",
        kind: "cosmetic",
        label: "Llama Character Skins",
        target_usd: "1.50",
        pricing: "mock-token-price-usd",
        amount_tlama: 150,
        description: "Cosmetic skin with no gameplay advantage.",
        variants: [
          { skin_id: "aurora", label: "Aurora llama skin", preview: { body: "#7ffcff", accent: "#ff66d8", glow: "#63f6ff" } },
          { skin_id: "midnight", label: "Midnight llama skin", preview: { body: "#7d72ff", accent: "#20e3ff", glow: "#8b5cff" } },
        ],
      },
    ],
  },
  catalog: [
    {
      id: "arcade-entry-fee",
      kind: "entry",
      label: "In-Game Entry Fee",
      target_usd: "0.25",
      pricing: "mock-token-price-usd",
      amount_tlama: 25,
      description: "Required once per arcade match.",
    },
    {
      id: "heart-matrix-upgrade",
      kind: "utility",
      label: "Heart Matrix Upgrade",
      target_usd: "1.50",
      pricing: "mock-token-price-usd",
      amount_tlama: 150,
      description: "Adds one life to this match, up to two upgrades.",
      unlock_level: 6,
      max_per_match: 2,
    },
    {
      id: "llama-character-skins",
      kind: "cosmetic",
      label: "Llama Character Skins",
      target_usd: "1.50",
      pricing: "mock-token-price-usd",
      amount_tlama: 150,
      description: "Cosmetic skin with no gameplay advantage.",
      variants: [
        { skin_id: "aurora", label: "Aurora llama skin", preview: { body: "#7ffcff", accent: "#ff66d8", glow: "#63f6ff" } },
        { skin_id: "midnight", label: "Midnight llama skin", preview: { body: "#7d72ff", accent: "#20e3ff", glow: "#8b5cff" } },
      ],
    },
  ],
};