import importlib.util
import json
import pathlib
import subprocess
import tempfile
import unittest


MODULE_PATH = pathlib.Path(__file__).with_name("verify_artifact_manifest.py")
SPEC = importlib.util.spec_from_file_location("manifest_verifier", MODULE_PATH)
verifier = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(verifier)

IDS = {
    "adapter": "11111111111111111111111111111112",
    "hook": "11111111111111111111111111111113",
    "tlamaMint": "11111111111111111111111111111114",
    "tlamaVault": "11111111111111111111111111111115",
    "wsolVault": "11111111111111111111111111111116",
    "poolAuthority": "11111111111111111111111111111117",
}


class ProductionManifestTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.root = pathlib.Path(self.temp.name)
        (self.root / verifier.PRODUCTION_IDS_PATH).parent.mkdir(parents=True)
        (self.root / verifier.PRODUCTION_IDS_PATH).write_text(
            "\n".join(f"{name}={value}" for name, value in IDS.items()) + "\n"
        )
        (self.root / verifier.DEVELOPMENT_IDS_PATH).write_text(
            "adapter=11111111111111111111111111111118\n"
        )
        for package in ("tlama-pool-hook", "tlama-transfer-hook"):
            base = self.root / "onchain" / package
            (base / "src").mkdir(parents=True)
            (base / "src" / "config.rs").write_text("// generated by build.rs\n")
            (base / "build.rs").write_text("// reads ../production-ids.txt\n")
            (base / "Cargo.toml").write_text("[package]\nname='x'\nversion='0.1.0'\n")
            (base / "Cargo.lock").write_text(f"{package} lock\n")
        for relative in verifier.RELEASE_VALIDATION_PATHS:
            path = self.root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists():
                path.write_text(f"{relative} validation fixture\n")
        self.git_run("git", "init", "-q")
        self.git_run("git", "config", "user.email", "test@example.invalid")
        self.git_run("git", "config", "user.name", "Test")
        self.git_run("git", "add", ".")
        self.git_run("git", "commit", "-qm", "freeze")
        self.commit = self.git_run("git", "rev-parse", "HEAD")
        self.artifacts = self.root / "artifacts"
        self.artifacts.mkdir()
        for name in verifier.RELEASE_ARTIFACTS + verifier.RELEASE_RUNTIME_ARTIFACTS:
            (self.artifacts / name).write_bytes(b"\x7fELFtest-" + name.encode())

    def tearDown(self):
        self.temp.cleanup()

    def git_run(self, *args):
        return subprocess.check_output(args, cwd=self.root, text=True).strip()

    def manifest(self):
        locks = {
            path: verifier.sha256_bytes(
                subprocess.check_output(
                    ["git", "show", f"{self.commit}:{path}"], cwd=self.root
                )
            )
            for path in verifier.REQUIRED_LOCKFILES
        }
        artifacts = {
            name: verifier.sha256(self.artifacts / name) for name in verifier.RELEASE_ARTIFACTS
        }
        runtime_artifacts = {
            name: verifier.sha256(self.artifacts / name)
            for name in verifier.RELEASE_RUNTIME_ARTIFACTS
        }
        toolchain = {
            name: {"version": "pinned", "archiveSha256": "a" * 64}
            for name in verifier.REQUIRED_TOOLCHAIN_FIELDS
        }
        evidence = {
            "schemaVersion": 1,
            "sourceCommit": self.commit,
            "toolchainArchives": {
                "agave": toolchain["agave"]["archiveSha256"],
                "platformTools": toolchain["platformTools"]["archiveSha256"],
            },
        }
        for build_name in ("buildA", "buildB"):
            evidence[build_name] = {
                name: {
                    "bytes": (self.artifacts / name).stat().st_size,
                    "sha256": artifacts[name],
                }
                for name in verifier.RELEASE_ARTIFACTS
            }
        evidence_path = self.artifacts / "reproducible-build.json"
        evidence_path.write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n")
        return {
            "schemaVersion": 3, "buildKind": "production",
            "sourceCommit": self.commit, "validationCommit": self.commit,
            "lockfiles": locks, "toolchain": toolchain,
            "ids": dict(IDS), "artifacts": artifacts,
            "runtimeArtifacts": runtime_artifacts,
            "reproducibleBuildEvidence": {
                "file": "reproducible-build.json",
                "sha256": verifier.sha256(evidence_path),
            },
        }

    def assert_rejected(self, manifest, message):
        with self.assertRaises(SystemExit) as error:
            verifier.verify(manifest, self.artifacts, self.root)
        self.assertIn(message, str(error.exception))

    def test_valid_production_manifest(self):
        verifier.verify(self.manifest(), self.artifacts, self.root)

    def test_frozen_source_can_be_verified_from_newer_documentation_commit(self):
        manifest = self.manifest()
        (self.root / "release-notes.md").write_text("manifest committed later\n")
        self.git_run("git", "add", "release-notes.md")
        self.git_run("git", "commit", "-qm", "commit release notes")
        verifier.verify(manifest, self.artifacts, self.root)

    def test_rejects_manifest_commit_from_unrelated_history(self):
        manifest = self.manifest()
        self.git_run("git", "checkout", "--orphan", "unrelated")
        self.git_run("git", "rm", "-rf", ".")
        (self.root / "unrelated.txt").write_text("unrelated\n")
        self.git_run("git", "add", "unrelated.txt")
        self.git_run("git", "commit", "-qm", "unrelated")
        self.assert_rejected(manifest, "not an ancestor")

    def test_rejects_malformed_hash_and_id(self):
        manifest = self.manifest()
        manifest["lockfiles"]["onchain/tlama-pool-hook/Cargo.lock"] = "A" * 64
        self.assert_rejected(manifest, "canonical lowercase")
        manifest = self.manifest()
        manifest["ids"]["adapter"] = "not-base58-0"
        self.assert_rejected(manifest, "valid 32-byte")

    def test_rejects_config_and_artifact_mismatch(self):
        manifest = self.manifest()
        manifest["ids"]["adapter"] = IDS["hook"]
        self.assert_rejected(manifest, "adapter and hook")
        manifest = self.manifest()
        (self.artifacts / "tlama_pool_adapter.so").write_bytes(b"\x7fELFmodified")
        self.assert_rejected(manifest, "artifact hash mismatch")
        manifest = self.manifest()
        (self.artifacts / "spl_token.so").write_bytes(b"\x7fELFmodified-runtime")
        self.assert_rejected(manifest, "artifact hash mismatch")

    def test_requires_runtime_and_reproducible_build_evidence(self):
        manifest = self.manifest()
        del manifest["runtimeArtifacts"]
        self.assert_rejected(manifest, "runtime artifacts must contain exactly")
        manifest = self.manifest()
        del manifest["reproducibleBuildEvidence"]
        self.assert_rejected(
            manifest, "reproducibleBuildEvidence must contain exactly"
        )

    def test_rejects_malformed_committed_id_input(self):
        (self.root / verifier.PRODUCTION_IDS_PATH).write_text("adapter=placeholder\n")
        self.git_run("git", "add", verifier.PRODUCTION_IDS_PATH)
        self.git_run("git", "commit", "-qm", "bad input")
        manifest = self.manifest()
        manifest["sourceCommit"] = self.git_run("git", "rev-parse", "HEAD")
        manifest["validationCommit"] = manifest["sourceCommit"]
        self.assert_rejected(manifest, "exactly six")

    def test_rejects_lock_mismatch_and_dirty_freeze(self):
        manifest = self.manifest()
        manifest["lockfiles"]["onchain/tlama-pool-hook/Cargo.lock"] = "b" * 64
        self.assert_rejected(manifest, "lockfile hash mismatch")
        # Commit a source change: evidence HEAD may be newer, but frozen
        # on-chain source must remain byte-for-byte unchanged.
        (self.root / "onchain/tlama-pool-hook/src/config.rs").write_text("changed")
        self.git_run("git", "add", ".")
        self.git_run("git", "commit", "-qm", "dirty after freeze")
        manifest = self.manifest()
        self.assert_rejected(manifest, "changed after sourceCommit")

    def test_rejects_validation_harness_changes(self):
        manifest = self.manifest()
        harness = self.root / verifier.RELEASE_VALIDATION_PATHS[0]
        harness.parent.mkdir(parents=True, exist_ok=True)
        harness.write_text("weakened")
        self.assert_rejected(manifest, "validation harness changed")

    def test_rejects_disposable_development_id_reuse(self):
        manifest = self.manifest()
        development_path = self.root / verifier.DEVELOPMENT_IDS_PATH
        development_path.write_text(f"adapter={IDS['adapter']}\n")
        self.git_run("git", "add", verifier.DEVELOPMENT_IDS_PATH)
        self.git_run("git", "commit", "-qm", "development IDs")
        manifest["sourceCommit"] = self.git_run("git", "rev-parse", "HEAD")
        manifest["validationCommit"] = manifest["sourceCommit"]
        manifest["lockfiles"] = {
            path: verifier.sha256_bytes(
                subprocess.check_output(
                    ["git", "show", f"{manifest['sourceCommit']}:{path}"],
                    cwd=self.root,
                )
            )
            for path in verifier.REQUIRED_LOCKFILES
        }
        self.assert_rejected(manifest, "reuses disposable development IDs")


if __name__ == "__main__":
    unittest.main()